#!/bin/sh

. /lib.subr

set -e

create_user

change_owner /app

teleirc_conf="/usr/local/etc/teleirc.conf"

if [ ! -s "${teleirc}" ]; then
    install -m 640 -o noroot -g noroot /dev/null /usr/local/etc/teleirc.conf

    TELEIRC_IRC_SERVER="${TELEIRC_IRC_SERVER:-irc.libera.chat}" \
    TELEIRC_IRC_PORT="${TELEIRC_IRC_PORT:-6697}" \
    TELEIRC_IRC_USE_SSL="${TELEIRC_IRC_USE_SSL:-true}" \
    TELEIRC_IRC_CERT_ALLOW_EXPIRED="${TELEIRC_IRC_CERT_ALLOW_EXPIRED:-false}" \
    TELEIRC_IRC_CERT_ALLOW_SELFSIGNED="${TELEIRC_IRC_CERT_ALLOW_SELFSIGNED:-false}" \
    TELEIRC_IRC_CHANNEL="${TELEIRC_IRC_CHANNEL:-#channel}" \
    TELEIRC_IRC_BOT_NAME="${TELEIRC_IRC_BOT_NAME:-tg-bridge-bot}" \
    TELEIRC_IRC_BOT_REALNAME="${TELEIRC_IRC_BOT_REALNAME:-Powered by TeleIRC <github.com/RITlug/teleirc>}" \
    TELEIRC_IRC_BOT_IDENT="${TELEIRC_IRC_BOT_IDENT:-teleirc}" \
    TELEIRC_IRC_NICKSERV_SERVICE="${TELEIRC_IRC_NICKSERV_SERVICE:-NickServ}" \
    TELEIRC_IRC_PREFIX="${TELEIRC_IRC_PREFIX:-<}" \
    TELEIRC_IRC_SUFFIX="${TELEIRC_IRC_SUFFIX:->}" \
    TELEIRC_IRC_SEND_STICKER_EMOJI="${TELEIRC_IRC_SEND_STICKER_EMOJI:-true}" \
    TELEIRC_IRC_SEND_DOCUMENT="${TELEIRC_IRC_SEND_DOCUMENT:-false}" \
    TELEIRC_IRC_EDITED_PREFIX="${TELEIRC_IRC_EDITED_PREFIX:-(edited) }" \
    TELEIRC_IRC_MAX_MESSAGE_LENGTH="${TELEIRC_IRC_MAX_MESSAGE_LENGTH:-400}" \
    TELEIRC_IRC_SHOW_ZWSP="${TELEIRC_IRC_SHOW_ZWSP:-true}" \
    TELEIRC_IRC_SHOW_LOCATION_MESSAGE="${TELEIRC_IRC_SHOW_LOCATION_MESSAGE:-false}" \
    TELEIRC_IRC_QUIT_MESSAGE="${TELEIRC_IRC_QUIT_MESSAGE:-TeleIRC bridge stopped.}" \
    TELEIRC_TELEGRAM_CHAT_ID="${TELEIRC_TELEGRAM_CHAT_ID:--0000000000000}" \
    TELEIRC_TELEIRC_TOKEN="${TELEIRC_TELEIRC_TOKEN:-000000000:AAAAAAaAAa2AaAAaoAAAA-a_aaAAaAaaaAA}" \
    TELEIRC_MAX_MESSAGES_PER_MINUTE="${TELEIRC_MAX_MESSAGES_PER_MINUTE:-20}" \
    TELEIRC_TELEGRAM_MESSAGE_REPLY_PREFIX="${TELEIRC_TELEGRAM_MESSAGE_REPLY_PREFIX:-[}" \
    TELEIRC_TELEGRAM_MESSAGE_REPLY_SUFFIX="${TELEIRC_TELEGRAM_MESSAGE_REPLY_SUFFIX:-]}" \
    TELEIRC_TELEGRAM_MESSAGE_REPLY_LENGTH="${TELEIRC_TELEGRAM_MESSAGE_REPLY_LENGTH:-15}" \
    TELEIRC_SHOW_TOPIC_MESSAGE="${TELEIRC_SHOW_TOPIC_MESSAGE:-true}" \
    TELEIRC_SHOW_ACTION_MESSAGE="${TELEIRC_SHOW_ACTION_MESSAGE:-true}" \
    TELEIRC_SHOW_JOIN_MESSAGE="${TELEIRC_SHOW_JOIN_MESSAGE:-false}" \
    TELEIRC_SHOW_KICK_MESSAGE="${TELEIRC_SHOW_KICK_MESSAGE:-true}" \
    TELEIRC_SHOW_NICK_MESSAGE="${TELEIRC_SHOW_NICK_MESSAGE:-false}" \
    TELEIRC_SHOW_LEAVE_MESSAGE="${TELEIRC_SHOW_LEAVE_MESSAGE:-false}" \
    TELEIRC_SHOW_DISCONNECT_MESSAGE="${TELEIRC_SHOW_DISCONNECT_MESSAGE:-true}" \
    TELEIRC_IMGUR_CLIENT_ID="${TELEIRC_IMGUR_CLIENT_ID:-7d6b00b87043f58}" \
        envsubst < /templates/teleirc.conf > /usr/local/etc/teleirc.conf
fi

if [ "${1#-}" != "$1" ]; then
    set -- teleirc "$@"
fi

if [ "$1" = "teleirc" ]; then
    set -- su-exec noroot "$@"
fi

exec "$@"
