# See the Config File Glossary for instructions.
# https://docs.teleirc.com/en/latest/user/config-file-glossary/

###############################################################################
#                                                                             #
#                       IRC configuration settings                            #
#                                                                             #
###############################################################################

#####----- Host connection settings -----#####
IRC_HOST_IP="${TELEIRC_IRC_HOST_IP}"


#####----- IRC server connection settings -----#####
IRC_SERVER="${TELEIRC_IRC_SERVER}"
IRC_SERVER_PASSWORD="${TELEIRC_IRC_SERVER_PASSWORD}"
IRC_PORT="${TELEIRC_IRC_PORT}"

## Encryption (SSL/TLS) options
IRC_USE_SSL="${TELEIRC_IRC_USE_SSL}"
IRC_CERT_ALLOW_EXPIRED="${TELEIRC_IRC_CERT_ALLOW_EXPIRED}"
IRC_CERT_ALLOW_SELFSIGNED="${TELEIRC_IRC_CERT_ALLOW_SELFSIGNED}"


#####----- IRC channel settings -----#####
IRC_CHANNEL="${TELEIRC_IRC_CHANNEL}"
IRC_CHANNEL_KEY="${TELEIRC_IRC_CHANNEL_KEY}"
IRC_BLACKLIST="${TELEIRC_IRC_BLACKLIST}"


#####----- IRC bot settings -----#####
IRC_BOT_NAME="${TELEIRC_IRC_BOT_NAME}"
IRC_BOT_REALNAME="${TELEIRC_IRC_BOT_REALNAME}"
IRC_BOT_IDENT="${TELEIRC_IRC_BOT_IDENT}"

# NickServ options
IRC_NICKSERV_SERVICE="${TELEIRC_IRC_NICKSERV_SERVICE}"
IRC_NICKSERV_USER="${TELEIRC_IRC_NICKSERV_USER}"
IRC_NICKSERV_PASS="${TELEIRC_IRC_NICKSERV_PASS}"


#####----- IRC message settings -----#####
IRC_PREFIX="${TELEIRC_IRC_PREFIX}"
IRC_SUFFIX="${TELEIRC_IRC_SUFFIX}"
IRC_SEND_STICKER_EMOJI="${TELEIRC_IRC_SEND_STICKER_EMOJI}"
IRC_SEND_DOCUMENT="${TELEIRC_IRC_SEND_DOCUMENT}"
IRC_EDITED_PREFIX="${TELEIRC_IRC_EDITED_PREFIX}"
IRC_MAX_MESSAGE_LENGTH="${TELEIRC_IRC_MAX_MESSAGE_LENGTH}"
IRC_SHOW_ZWSP="${TELEIRC_IRC_SHOW_ZWSP}"
IRC_SHOW_LOCATION_MESSAGE="${TELEIRC_IRC_SHOW_LOCATION_MESSAGE}"
IRC_NO_FORWARD_PREFIX="${TELEIRC_IRC_NO_FORWARD_PREFIX}"
IRC_QUIT_MESSAGE="${TELEIRC_IRC_QUIT_MESSAGE}"



###############################################################################
#                                                                             #
#                     Telegram configuration settings                         #
#                                                                             #
###############################################################################

TELEGRAM_CHAT_ID="${TELEIRC_TELEGRAM_CHAT_ID}"
TELEIRC_TOKEN="${TELEIRC_TELEIRC_TOKEN}"
MAX_MESSAGES_PER_MINUTE="${TELEIRC_MAX_MESSAGES_PER_MINUTE}"
TELEGRAM_MESSAGE_REPLY_PREFIX="${TELEIRC_TELEGRAM_MESSAGE_REPLY_PREFIX}"
TELEGRAM_MESSAGE_REPLY_SUFFIX="${TELEIRC_TELEGRAM_MESSAGE_REPLY_SUFFIX}"
TELEGRAM_MESSAGE_REPLY_LENGTH="${TELEIRC_TELEGRAM_MESSAGE_REPLY_LENGTH}"
SHOW_TOPIC_MESSAGE="${TELEIRC_SHOW_TOPIC_MESSAGE}"
SHOW_ACTION_MESSAGE="${TELEIRC_SHOW_ACTION_MESSAGE}"
SHOW_JOIN_MESSAGE="${TELEIRC_SHOW_JOIN_MESSAGE}"
JOIN_MESSAGE_ALLOW_LIST="${TELEIRC_JOIN_MESSAGE_ALLOW_LIST}"
SHOW_KICK_MESSAGE="${TELEIRC_SHOW_KICK_MESSAGE}"
SHOW_NICK_MESSAGE="${TELEIRC_SHOW_NICK_MESSAGE}"
SHOW_LEAVE_MESSAGE="${TELEIRC_SHOW_LEAVE_MESSAGE}"
LEAVE_MESSAGE_ALLOW_LIST="${TELEIRC_LEAVE_MESSAGE_ALLOW_LIST}"
SHOW_DISCONNECT_MESSAGE="${TELEIRC_SHOW_DISCONNECT_MESSAGE}"


################################################################################
#                                                                             #
#                      Imgur configuration settings                           #
#                                                                             #
###############################################################################

IMGUR_CLIENT_ID="${TELEIRC_IMGUR_CLIENT_ID}"
IMGUR_CLIENT_SECRET="${TELEIRC_IMGUR_CLIENT_SECRET}"
IMGUR_REFRESH_TOKEN="${TELEIRC_IMGUR_REFRESH_TOKEN}"
IMGUR_ALBUM_HASH="${TELEIRC_IMGUR_ALBUM_HASH}"
